/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Fernando
 */
public class Habitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Habitacion
     */
    public Habitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1Activo = new javax.swing.JRadioButton();
        jComboBox2ItemCategoria = new javax.swing.JComboBox<>();
        jButton1Modificar = new javax.swing.JButton();
        jButton2Eliminar = new javax.swing.JButton();
        jButton3Buscar = new javax.swing.JButton();
        jButton4Salir = new javax.swing.JButton();
        jLabel1Habitacion = new javax.swing.JLabel();
        jButton5Guardar = new javax.swing.JButton();
        jLabel2Piso = new javax.swing.JLabel();
        jLabel3Estado = new javax.swing.JLabel();
        jLabel4Categoria = new javax.swing.JLabel();
        jComboBox1ItemPiso = new javax.swing.JComboBox<>();

        jComboBox2ItemCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1Modificar.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1Modificar.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Modificar.setText("Modificar");

        jButton2Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        jButton2Eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButton2Eliminar.setText("Eliminar");

        jButton3Buscar.setBackground(new java.awt.Color(0, 0, 0));
        jButton3Buscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton3Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/busqueda.png"))); // NOI18N
        jButton3Buscar.setText("Buscar");

        jButton4Salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton4Salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Salir.setText("Salir");

        jLabel1Habitacion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1Habitacion.setText("Habitación");

        jButton5Guardar.setBackground(new java.awt.Color(0, 0, 0));
        jButton5Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton5Guardar.setText("Guardar");

        jLabel2Piso.setText("Piso:");

        jLabel3Estado.setText("Estado:");

        jLabel4Categoria.setText("Categoria:");

        jComboBox1ItemPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1ItemPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ItemPisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2Piso)
                            .addComponent(jLabel3Estado)
                            .addComponent(jLabel4Categoria))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2ItemCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1Activo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1ItemPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3Buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1Modificar)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4Salir)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1Habitacion)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1Habitacion)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Piso)
                    .addComponent(jComboBox1ItemPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3Buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2ItemCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4Categoria))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Estado)
                    .addComponent(jRadioButton1Activo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Modificar)
                    .addComponent(jButton2Eliminar)
                    .addComponent(jButton4Salir)
                    .addComponent(jButton5Guardar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ItemPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemPisoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Modificar;
    private javax.swing.JButton jButton2Eliminar;
    private javax.swing.JButton jButton3Buscar;
    private javax.swing.JButton jButton4Salir;
    private javax.swing.JButton jButton5Guardar;
    private javax.swing.JComboBox<String> jComboBox1ItemPiso;
    private javax.swing.JComboBox<String> jComboBox2ItemCategoria;
    private javax.swing.JLabel jLabel1Habitacion;
    private javax.swing.JLabel jLabel2Piso;
    private javax.swing.JLabel jLabel3Estado;
    private javax.swing.JLabel jLabel4Categoria;
    private javax.swing.JRadioButton jRadioButton1Activo;
    // End of variables declaration//GEN-END:variables
}
