/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Fernando
 */
public class Huesped extends javax.swing.JInternalFrame {

    /**
     * Creates new form Huesped
     */
    public Huesped() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3Nombre = new javax.swing.JLabel();
        jButton1Guardar = new javax.swing.JButton();
        jLabel4Dni = new javax.swing.JLabel();
        jButton2Modicar = new javax.swing.JButton();
        jLabel5Correo = new javax.swing.JLabel();
        jButton3Eliminar = new javax.swing.JButton();
        jLabel6Celular = new javax.swing.JLabel();
        jButton4Salir = new javax.swing.JButton();
        jLabel7Domicilio = new javax.swing.JLabel();
        jButton5Buscar = new javax.swing.JButton();
        jTextField1Ape = new javax.swing.JTextField();
        jTextField2Nom = new javax.swing.JTextField();
        jTextField3Dn = new javax.swing.JTextField();
        jTextField4Corre = new javax.swing.JTextField();
        jLabel1Huesped = new javax.swing.JLabel();
        jTextField5Celula = new javax.swing.JTextField();
        jLabel2Apellido = new javax.swing.JLabel();
        jTextField6Domici = new javax.swing.JTextField();

        jLabel3Nombre.setText("Nombre:");

        jButton1Guardar.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Guardar.setText("Guardar");

        jLabel4Dni.setText("DNI:");

        jButton2Modicar.setBackground(new java.awt.Color(0, 0, 0));
        jButton2Modicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2Modicar.setForeground(new java.awt.Color(255, 255, 255));
        jButton2Modicar.setText("Modificar");

        jLabel5Correo.setText("Correo:");

        jButton3Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        jButton3Eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButton3Eliminar.setText("Eliminar");

        jLabel6Celular.setText("Celular:");

        jButton4Salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton4Salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Salir.setText("Salir");

        jLabel7Domicilio.setText("Domicilio:");

        jButton5Buscar.setBackground(new java.awt.Color(0, 0, 0));
        jButton5Buscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton5Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/busqueda.png"))); // NOI18N
        jButton5Buscar.setText("Buscar");
        jButton5Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5BuscarActionPerformed(evt);
            }
        });

        jLabel1Huesped.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1Huesped.setText("Huesped");

        jLabel2Apellido.setText("Apellido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1Guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2Apellido)
                            .addComponent(jLabel3Nombre)
                            .addComponent(jLabel4Dni)
                            .addComponent(jLabel5Correo)
                            .addComponent(jLabel6Celular)
                            .addComponent(jLabel7Domicilio))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2Modicar)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3Eliminar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1Ape)
                        .addComponent(jTextField2Nom)
                        .addComponent(jTextField3Dn)
                        .addComponent(jTextField4Corre)
                        .addComponent(jTextField5Celula)
                        .addComponent(jTextField6Domici, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1Huesped)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4Salir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5Buscar)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1Huesped)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Apellido)
                    .addComponent(jTextField1Ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jTextField2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3Dn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Correo)
                    .addComponent(jTextField4Corre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Celular)
                    .addComponent(jTextField5Celula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7Domicilio)
                    .addComponent(jTextField6Domici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Guardar)
                    .addComponent(jButton2Modicar)
                    .addComponent(jButton3Eliminar)
                    .addComponent(jButton4Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Guardar;
    private javax.swing.JButton jButton2Modicar;
    private javax.swing.JButton jButton3Eliminar;
    private javax.swing.JButton jButton4Salir;
    private javax.swing.JButton jButton5Buscar;
    private javax.swing.JLabel jLabel1Huesped;
    private javax.swing.JLabel jLabel2Apellido;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Dni;
    private javax.swing.JLabel jLabel5Correo;
    private javax.swing.JLabel jLabel6Celular;
    private javax.swing.JLabel jLabel7Domicilio;
    private javax.swing.JTextField jTextField1Ape;
    private javax.swing.JTextField jTextField2Nom;
    private javax.swing.JTextField jTextField3Dn;
    private javax.swing.JTextField jTextField4Corre;
    private javax.swing.JTextField jTextField5Celula;
    private javax.swing.JTextField jTextField6Domici;
    // End of variables declaration//GEN-END:variables
}
