/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasFinalesNO;

import hotelgrupo90.accesoADatos.Conexion;
import hotelgrupo90.accesoADatos.HabitacionData;
import hotelgrupo90.accesoADatos.ReservaData;
import hotelgrupo90.entidades.Habitacion;
import hotelgrupo90.entidades.Reserva;
import hotelgrupo90.entidades.TipoHabitacion;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MenuReserva extends javax.swing.JInternalFrame {
 private  ReservaData reservaData = new ReservaData();
    private  Reserva reservaActual=null;
  private HabitacionData habitacionData= new HabitacionData();
  private Habitacion habitacionActual = null;
    
    public MenuReserva() {
        initComponents();
         reservaData = new ReservaData();
         
       
        Conexion.getConexion();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon(getClass().getResource("/Recursos/sombra1.png"));
        Image miImage = icono.getImage();
        Escritorio3 = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(miImage,0,0,getWidth(),getHeight(),this);
            }};
            jLabel1 = new javax.swing.JLabel();
            jLabel2Entrada = new javax.swing.JLabel();
            jLabel3Salida = new javax.swing.JLabel();
            jButton1Buscar = new javax.swing.JButton();
            jButton2Salir = new javax.swing.JButton();
            jTextField1Buscar = new javax.swing.JTextField();
            jDateChooser1Entrada = new com.toedter.calendar.JDateChooser();
            jDateChooser2Salida = new com.toedter.calendar.JDateChooser();
            jTextField1Personas = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jTextField2CantidadC = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jTextField3Camas = new javax.swing.JTextField();
            jTextField4Precio = new javax.swing.JTextField();
            jTextField1PrecioFinal = new javax.swing.JTextField();
            jLabel6 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();

            Escritorio3.setBackground(new java.awt.Color(255, 255, 255));
            Escritorio3.setMaximumSize(new java.awt.Dimension(500, 500));
            Escritorio3.setMinimumSize(new java.awt.Dimension(500, 500));
            Escritorio3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setBackground(new java.awt.Color(255, 255, 255));
            jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Información de Reserva");
            Escritorio3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, -1, -1));

            jLabel2Entrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel2Entrada.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2Entrada.setText("Entrada:");
            Escritorio3.add(jLabel2Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 102, -1, -1));

            jLabel3Salida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel3Salida.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3Salida.setText("Salida:");
            Escritorio3.add(jLabel3Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 139, 60, -1));

            jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
            jButton1Buscar.setText("Buscar");
            jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1BuscarActionPerformed(evt);
                }
            });
            Escritorio3.add(jButton1Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 125, -1, -1));

            jButton2Salir.setText("Salir");
            jButton2Salir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2SalirActionPerformed(evt);
                }
            });
            Escritorio3.add(jButton2Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 427, -1, -1));

            jTextField1Buscar.setText("1");
            Escritorio3.add(jTextField1Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 127, 54, -1));
            Escritorio3.add(jDateChooser1Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 99, -1, -1));
            Escritorio3.add(jDateChooser2Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 148, -1, -1));
            Escritorio3.add(jTextField1Personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 224, 87, -1));

            jLabel2.setText("Cantidad de Personas: ");
            Escritorio3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, -1, -1));
            Escritorio3.add(jTextField2CantidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 277, 87, -1));

            jLabel3.setText("Cantidad de Camas");
            Escritorio3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

            jLabel4.setText("Tipos de Cama");
            Escritorio3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 227, 84, -1));

            jLabel5.setText("Precio: ");
            Escritorio3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 280, -1, -1));
            Escritorio3.add(jTextField3Camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 224, 129, -1));
            Escritorio3.add(jTextField4Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 277, 129, -1));

            jTextField1PrecioFinal.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1PrecioFinalActionPerformed(evt);
                }
            });
            Escritorio3.add(jTextField1PrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

            jLabel6.setText("Precio Total:");
            Escritorio3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 30));

            jButton1.setText("Calcular Precio");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            Escritorio3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Escritorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Escritorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SalirActionPerformed
dispose();
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2SalirActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
       try {
             
            Integer id = Integer.parseInt(jTextField1Buscar.getText());
           
             habitacionActual = habitacionData.buscarHabitacionPorTipo(id);
           
             if (habitacionActual!=null) {
          jTextField3Camas.setText(habitacionActual.getTipo_habitacion().getTipoCamas());
          jTextField2CantidadC.setText(String.valueOf(habitacionActual.getTipo_habitacion().getCantidadCamas()));
          jTextField1Personas.setText(String.valueOf(habitacionActual.getTipo_habitacion().getCantidadPersonas()));
          jTextField4Precio.setText(String.valueOf(habitacionActual.getTipo_habitacion().getPrecio()));
  
      
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showConfirmDialog(null, "Debe ingresar datos validos");
        }
        
                                       
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jTextField1PrecioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1PrecioFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PrecioFinalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (Integer.parseInt(jTextField1Buscar.getText())==1 ) {
                
               Date entrada = jDateChooser1Entrada.getDate();
                
               Date salida = jDateChooser2Salida.getDate();
               
               if(entrada.before(salida)){
               
               int dias = (int)((salida.getTime()- entrada.getTime())/86400000);
               
               double precio= 800 * dias;
               
               jTextField1PrecioFinal.setText(precio + " ");
            //   JOptionPane.showMessageDialog(this, "ingrese las fechas correctamente.");
               }
               
                      
            }else if (Integer.parseInt(jTextField1Buscar.getText())==2) {
                
                Date entrada = jDateChooser1Entrada.getDate();
                
               Date salida = jDateChooser2Salida.getDate();
               if(entrada.before(salida)){
               int dias = (int)((salida.getTime()- entrada.getTime())/86400000);
               
               double precio= 700 * dias;
               
               jTextField1PrecioFinal.setText(precio + " ");
               }
               
            }else if (Integer.parseInt(jTextField1Buscar.getText())==3) {
                
                Date entrada = jDateChooser1Entrada.getDate();
                
               Date salida = jDateChooser2Salida.getDate();
               if(entrada.before(salida)){
               
               int dias = (int)((salida.getTime()- entrada.getTime())/86400000);
               
               double precio= 500 * dias;
               
               jTextField1PrecioFinal.setText(precio + " ");
               }
               
            }else if (Integer.parseInt(jTextField1Buscar.getText())==4) {
                
                Date entrada = jDateChooser1Entrada.getDate();
                
               Date salida = jDateChooser2Salida.getDate();
               if(entrada.before(salida)){
               
               int dias = (int)((salida.getTime()- entrada.getTime())/86400000);
               
               double precio= 300 * dias;
               
               jTextField1PrecioFinal.setText(precio + " ");
               }
            }
                
            
            
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed
  /*private void armarCabeceraTabla(){
        
        ArrayList<Object> fila = new ArrayList<>();
        fila.add("id");
        fila.add("Cantidad de Personas");
        fila.add("cantidad de camas");
        fila.add("Tipo de Cama");
        fila.add("Precio");
        
        for (Object it: fila){
         modelo.addColumn(it);
        }
        jTable1Tabla.setModel(modelo);
        
 
 }
    private void BorrarFila(){
      int indice = modelo.getRowCount() -1;
      
      for (int i = indice;i>= 0;i --){
          
          modelo.removeRow(i);
      }
        
   }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton2Salir;
    private com.toedter.calendar.JDateChooser jDateChooser1Entrada;
    private com.toedter.calendar.JDateChooser jDateChooser2Salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Entrada;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Salida;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1Buscar;
    private javax.swing.JTextField jTextField1Personas;
    private javax.swing.JTextField jTextField1PrecioFinal;
    private javax.swing.JTextField jTextField2CantidadC;
    private javax.swing.JTextField jTextField3Camas;
    private javax.swing.JTextField jTextField4Precio;
    // End of variables declaration//GEN-END:variables
}
