/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasFinalesNO;

import hotelgrupo90.accesoADatos.Conexion;
import hotelgrupo90.accesoADatos.HuespedData;
import hotelgrupo90.entidades.Huesped;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class MenuHuesped extends javax.swing.JInternalFrame {
private HuespedData  huespedData = new HuespedData();
    private Huesped huespedActual = null;
     
    /**
     * Creates new form MenuHuesped
     */
    public MenuHuesped() {
        initComponents();
           Conexion.getConexion();
        huespedData = new HuespedData();
       ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        ImageIcon icono=new ImageIcon(getClass().getResource("/Recursos/sombra.png"));
        Image miImage = icono.getImage();
        Escritorio2 = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(miImage,0,0,getWidth(),getHeight(),this);
            }};
            jLabel1 = new javax.swing.JLabel();
            jLabel2Apellido = new javax.swing.JLabel();
            jTextField1Apellido = new javax.swing.JTextField();
            jLabel3Nombre = new javax.swing.JLabel();
            jTextField2Nombre = new javax.swing.JTextField();
            jLabel4Dni = new javax.swing.JLabel();
            jTextField3TextoDni = new javax.swing.JTextField();
            jLabel5Correo = new javax.swing.JLabel();
            jTextField4TextoCelular = new javax.swing.JTextField();
            jLabel6Domicilio = new javax.swing.JLabel();
            jTextField5TextoDomicilio = new javax.swing.JTextField();
            jLabel7Celular = new javax.swing.JLabel();
            jTextField6TextoCorreo = new javax.swing.JTextField();
            jButton1Guardar = new javax.swing.JButton();
            jButton2Nuevo = new javax.swing.JButton();
            jButton3Elminar = new javax.swing.JButton();
            jButton4Salir = new javax.swing.JButton();
            jButton5Buscar = new javax.swing.JButton();
            jTextField1IdBuscar = new javax.swing.JTextField();

            jTextField7.setText("jTextField7");

            Escritorio2.setBackground(new java.awt.Color(255, 255, 255));
            Escritorio2.setMaximumSize(new java.awt.Dimension(500, 500));
            Escritorio2.setMinimumSize(new java.awt.Dimension(500, 500));

            jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Registro de Huesped");

            jLabel2Apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel2Apellido.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2Apellido.setText("Apellido:");

            jTextField1Apellido.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ApellidoActionPerformed(evt);
                }
            });
            jTextField1Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField1ApellidoKeyTyped(evt);
                }
            });

            jLabel3Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel3Nombre.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3Nombre.setText("Nombre:");

            jTextField2Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField2NombreKeyTyped(evt);
                }
            });

            jLabel4Dni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel4Dni.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4Dni.setText("DNI:");

            jTextField3TextoDni.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField3TextoDniKeyTyped(evt);
                }
            });

            jLabel5Correo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel5Correo.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5Correo.setText("Correo:");

            jTextField4TextoCelular.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField4TextoCelularKeyTyped(evt);
                }
            });

            jLabel6Domicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel6Domicilio.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6Domicilio.setText("Domicilio:");

            jLabel7Celular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel7Celular.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7Celular.setText("Celular:");

            jButton1Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/disco-flexible.png"))); // NOI18N
            jButton1Guardar.setText("Guardar");
            jButton1Guardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1GuardarActionPerformed(evt);
                }
            });

            jButton2Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar (1).png"))); // NOI18N
            jButton2Nuevo.setText("Nuevo");
            jButton2Nuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2NuevoActionPerformed(evt);
                }
            });

            jButton3Elminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/circulo-marca-x (1).png"))); // NOI18N
            jButton3Elminar.setText("Eliminar");
            jButton3Elminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ElminarActionPerformed(evt);
                }
            });

            jButton4Salir.setText("Salir");
            jButton4Salir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4SalirActionPerformed(evt);
                }
            });

            jButton5Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
            jButton5Buscar.setText("Buscar");
            jButton5Buscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5BuscarActionPerformed(evt);
                }
            });

            jTextField1IdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField1IdBuscarKeyTyped(evt);
                }
            });

            Escritorio2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel2Apellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField1Apellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel3Nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField2Nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel4Dni, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField3TextoDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel5Correo, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField4TextoCelular, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel6Domicilio, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField5TextoDomicilio, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jLabel7Celular, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField6TextoCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jButton1Guardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jButton2Nuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jButton3Elminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jButton4Salir, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jButton5Buscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
            Escritorio2.setLayer(jTextField1IdBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout Escritorio2Layout = new javax.swing.GroupLayout(Escritorio2);
            Escritorio2.setLayout(Escritorio2Layout);
            Escritorio2Layout.setHorizontalGroup(
                Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Escritorio2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1Guardar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton2Nuevo)
                    .addGap(18, 18, 18)
                    .addComponent(jButton3Elminar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4Salir)
                    .addGap(29, 29, 29))
                .addGroup(Escritorio2Layout.createSequentialGroup()
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Escritorio2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4Dni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Escritorio2Layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3TextoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)
                                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Escritorio2Layout.createSequentialGroup()
                                            .addComponent(jLabel5Correo)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField6TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Escritorio2Layout.createSequentialGroup()
                                            .addComponent(jLabel7Celular)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField4TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Escritorio2Layout.createSequentialGroup()
                                            .addComponent(jLabel6Domicilio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(Escritorio2Layout.createSequentialGroup()
                                                    .addComponent(jTextField1IdBuscar)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton5Buscar))
                                                .addComponent(jTextField5TextoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(Escritorio2Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jLabel1)))
                    .addContainerGap(38, Short.MAX_VALUE))
            );
            Escritorio2Layout.setVerticalGroup(
                Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Escritorio2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(77, 77, 77)
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2Apellido)
                        .addComponent(jLabel7Celular)
                        .addComponent(jTextField4TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3Nombre)
                        .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5Correo)
                        .addComponent(jTextField6TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4Dni)
                            .addComponent(jTextField3TextoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6Domicilio)
                            .addComponent(jTextField5TextoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5Buscar)
                        .addComponent(jTextField1IdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                    .addGroup(Escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1Guardar)
                        .addComponent(jButton2Nuevo)
                        .addComponent(jButton3Elminar)
                        .addComponent(jButton4Salir))
                    .addGap(82, 82, 82))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Escritorio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Escritorio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton4SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4SalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4SalirActionPerformed

    private void jTextField1ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ApellidoActionPerformed

    private void jButton5BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5BuscarActionPerformed
        try {
            
       Integer id =Integer.parseInt(jTextField1IdBuscar.getText()) ;
       huespedActual = huespedData.bucarHuesped(id);
        //Integer dni = Integer.parseInt(jTextField3TextoDni.getText());
        //huespedActual= huespedData.buscarHuespedPorDni(dni);
       
        if (huespedActual!=null){
    
     jTextField1Apellido.setText(huespedActual.getApellido());
     jTextField2Nombre.setText(huespedActual.getNombre());
      jTextField3TextoDni.setText(String.valueOf(huespedActual.getDni()));
       jTextField6TextoCorreo.setText(huespedActual.getCorreo());
     jTextField5TextoDomicilio.setText(huespedActual.getDomicilio());
    jTextField4TextoCelular.setText(String.valueOf(huespedActual.getCelular()));
       // jTextField3Anio.setText(mat(huesped.getCelular());
        }
     } catch (NumberFormatException ex ) {
         JOptionPane.showConfirmDialog(this, "Debe ingresar numeros correctos");
        }
       
    }//GEN-LAST:event_jButton5BuscarActionPerformed

    private void jButton3ElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ElminarActionPerformed
         if(huespedActual!=null){


            huespedData.eliminarHuesped(huespedActual.getIdHuesped());

            huespedActual=null;

            limpiarCampos();

        }else{

            JOptionPane.showMessageDialog(this,"no hay Huesped seleccionado");
}



        // TODO add your handling code here:
    }                                                

    private void limpiarCampos(){
      
        
       jTextField3TextoDni.setText("");
       jTextField1Apellido.setText("");
       jTextField2Nombre.setText("");
       jTextField4TextoCelular.setText("");
       jTextField5TextoDomicilio.setText("");
       jTextField6TextoCorreo.setText("");
       jTextField1IdBuscar.setText("");
      
       
    }//GEN-LAST:event_jButton3ElminarActionPerformed

    private void jButton2NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2NuevoActionPerformed
          limpiarCampos();
    huespedActual= null;
    }//GEN-LAST:event_jButton2NuevoActionPerformed

    private void jTextField1ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1ApellidoKeyTyped
        if (!(Character.isLetter(evt.getKeyChar())) && ! (evt.getKeyChar()== KeyEvent.VK_SPACE)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField1ApellidoKeyTyped

    private void jTextField2NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2NombreKeyTyped
    if (!(Character.isLetter(evt.getKeyChar())) && ! (evt.getKeyChar()== KeyEvent.VK_SPACE)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField2NombreKeyTyped

    private void jTextField3TextoDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3TextoDniKeyTyped
        if (!(Character.isDigit(evt.getKeyChar())) && ! (evt.getKeyChar()== KeyEvent.VK_SPACE)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField3TextoDniKeyTyped

    private void jTextField4TextoCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4TextoCelularKeyTyped
        if (!(Character.isDigit(evt.getKeyChar())) && ! (evt.getKeyChar()== KeyEvent.VK_SPACE)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField4TextoCelularKeyTyped

    private void jTextField1IdBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1IdBuscarKeyTyped
          if (!(Character.isDigit(evt.getKeyChar())) && ! (evt.getKeyChar()== KeyEvent.VK_SPACE)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField1IdBuscarKeyTyped

    private void jButton1GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarActionPerformed
  try{
    Integer dni = Integer.parseInt(jTextField3TextoDni.getText());
    String nombre=jTextField2Nombre.getText();
    String apellido=jTextField1Apellido.getText();
    String correo=jTextField6TextoCorreo.getText();
    Integer celular = Integer.parseInt(jTextField4TextoCelular.getText());
    String domicilio= jTextField5TextoDomicilio.getText();

    if(nombre.isEmpty()|| apellido.isEmpty()){
      
        JOptionPane.showMessageDialog(this, "no puede haber campos vacios");
        return;
}


if(huespedActual==null){
   
   huespedActual=new Huesped (apellido, nombre, dni, correo, domicilio, celular);
    huespedData.guardadHuesped(huespedActual);

}else{

  
huespedActual.setApellido(apellido);
huespedActual.setNombre(nombre);
huespedActual.setDni(dni);
huespedActual.setCorreo(correo);
huespedActual.setCelular(celular);
huespedActual.setDomicilio(domicilio);

huespedData.modificarHuesped(huespedActual);

}


}catch(NumberFormatException nfe){

   JOptionPane.showMessageDialog(this, "Debe ingresar datos valido");

}
    }//GEN-LAST:event_jButton1GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio2;
    private javax.swing.JButton jButton1Guardar;
    private javax.swing.JButton jButton2Nuevo;
    private javax.swing.JButton jButton3Elminar;
    private javax.swing.JButton jButton4Salir;
    private javax.swing.JButton jButton5Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Apellido;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Dni;
    private javax.swing.JLabel jLabel5Correo;
    private javax.swing.JLabel jLabel6Domicilio;
    private javax.swing.JLabel jLabel7Celular;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1Apellido;
    private javax.swing.JTextField jTextField1IdBuscar;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField3TextoDni;
    private javax.swing.JTextField jTextField4TextoCelular;
    private javax.swing.JTextField jTextField5TextoDomicilio;
    private javax.swing.JTextField jTextField6TextoCorreo;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
