/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasFinalesNO;

/**
 *
 * @author Fernando
 */
public class MenuOpcional extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpcional
     */
    public MenuOpcional() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1RegistrodeHabitacion = new javax.swing.JMenu();
        jMenuItem5RegistroHabitacion = new javax.swing.JMenuItem();
        jMenu2RegistrodeHuesped = new javax.swing.JMenu();
        jMenuItem3RegistroHuesped = new javax.swing.JMenuItem();
        jMenuFormulariodeReserva = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem1ConfirmarReservas = new javax.swing.JMenuItem();
        jMenu4Salir = new javax.swing.JMenu();
        jMenuItem8CerrarVentana = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/hgg.png"))); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1RegistrodeHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/puerta (1).png"))); // NOI18N
        jMenu1RegistrodeHabitacion.setText("Habitación");

        jMenuItem5RegistroHabitacion.setText("Registro de habitacion");
        jMenuItem5RegistroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5RegistroHabitacionActionPerformed(evt);
            }
        });
        jMenu1RegistrodeHabitacion.add(jMenuItem5RegistroHabitacion);

        jMenuBar1.add(jMenu1RegistrodeHabitacion);

        jMenu2RegistrodeHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (4).png"))); // NOI18N
        jMenu2RegistrodeHuesped.setText("Huesped");
        jMenu2RegistrodeHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2RegistrodeHuespedActionPerformed(evt);
            }
        });

        jMenuItem3RegistroHuesped.setText("Registro de huesped");
        jMenuItem3RegistroHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3RegistroHuespedActionPerformed(evt);
            }
        });
        jMenu2RegistrodeHuesped.add(jMenuItem3RegistroHuesped);

        jMenuBar1.add(jMenu2RegistrodeHuesped);

        jMenuFormulariodeReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/anadir (1).png"))); // NOI18N
        jMenuFormulariodeReserva.setText("Rerserva");

        jMenuItem10.setText("Formulario de reserva");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuFormulariodeReserva.add(jMenuItem10);

        jMenuItem1ConfirmarReservas.setText("Confirmar la reserva");
        jMenuItem1ConfirmarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ConfirmarReservasActionPerformed(evt);
            }
        });
        jMenuFormulariodeReserva.add(jMenuItem1ConfirmarReservas);

        jMenuBar1.add(jMenuFormulariodeReserva);

        jMenu4Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar (1).png"))); // NOI18N
        jMenu4Salir.setText("Salir");

        jMenuItem8CerrarVentana.setText("Cerrar ventana");
        jMenuItem8CerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8CerrarVentanaActionPerformed(evt);
            }
        });
        jMenu4Salir.add(jMenuItem8CerrarVentana);

        jMenuBar1.add(jMenu4Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5RegistroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5RegistroHabitacionActionPerformed
       label.removeAll();
        label.repaint();
        MenuHabitacion cuarto = new MenuHabitacion();
        cuarto.setVisible(true);
        // cuarto.getContentPane().setBackground(new Color(68,167,132));
        label.add(cuarto);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5RegistroHabitacionActionPerformed

    private void jMenuItem3RegistroHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3RegistroHuespedActionPerformed

        label.removeAll();
        label.repaint();
        MenuHuesped cuarto = new MenuHuesped();
        cuarto.setVisible(true);
        // cuarto.getContentPane().setBackground(new Color(68,167,132));
       label.add(cuarto);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3RegistroHuespedActionPerformed

    private void jMenu2RegistrodeHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2RegistrodeHuespedActionPerformed

        // TODO add your handling code here:
        label.removeAll();
        label.repaint();
        MenuHuesped cuarto = new MenuHuesped();
        cuarto.setVisible(true);
        // cuarto.getContentPane().setBackground(new Color(68,167,132));
       label.add(cuarto);
    }//GEN-LAST:event_jMenu2RegistrodeHuespedActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        label.removeAll();
        label.repaint();
        MenuReserva cuarto = new MenuReserva();
        cuarto.setVisible(true);
        // cuarto.getContentPane().setBackground(new Color(68,167,132));
        label.add(cuarto);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8CerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8CerrarVentanaActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8CerrarVentanaActionPerformed

    private void jMenuItem1ConfirmarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ConfirmarReservasActionPerformed
      label.removeAll();
        label.repaint();
        MenuConfirmacion cuarto = new MenuConfirmacion();
        cuarto.setVisible(true);
        // cuarto.getContentPane().setBackground(new Color(68,167,132));
        label.add(cuarto);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ConfirmarReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1RegistrodeHabitacion;
    private javax.swing.JMenu jMenu2RegistrodeHuesped;
    private javax.swing.JMenu jMenu4Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFormulariodeReserva;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem1ConfirmarReservas;
    private javax.swing.JMenuItem jMenuItem3RegistroHuesped;
    private javax.swing.JMenuItem jMenuItem5RegistroHabitacion;
    private javax.swing.JMenuItem jMenuItem8CerrarVentana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
